name: Deploy to Google Apps Script

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build project
      run: yarn build
    
    - name: Setup Google Apps Script
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPS_SCRIPT_CREDENTIALS }}
    
    - name: Deploy to Dev
      run: |
        cp .clasp.dev.json .clasp.json
        npx clasp push
      env:
        CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build project
      run: yarn build
    
    - name: Setup Google Apps Script
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPS_SCRIPT_CREDENTIALS }}
    
    - name: Deploy to Production
      run: |
        cp .clasp.prod.json .clasp.json
        npx clasp push
      env:
        CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Automated deployment to production template sheet.
          
          Changes in this release:
          - Automated deployment from main branch
          - Template sheet updated with latest features
        draft: false
        prerelease: false 